project:
  name: qs-workshop
  regions:
  - eu-central-1
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - eu-central-1    
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: tobias.meyer@kreuzwerker.ch
      KeyPairName: XW-DK-Tobias
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "qs-workshop/"
      QSS3BucketName: "$[taskcat_autobucket]"

